/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HelveticaNeueLT Pro 45 Lt41.c                         *
* Font:        HelveticaNeueLT Pro 45 Lt                             *
* Height:      41                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 41                                            *
* Range disabled: 0000 - FFFF                                        *
* Range enabled:  0025 - 0025                                        *
* Range enabled:  002F - 002F                                        *
* Edit/Shift/Down    at character 0x25 (37)                          *
* Edit/Shift/Down    at character 0x25 (37)                          *
* Edit/Shift/Down    at character 0x25 (37)                          *
* Edit/Shift/Up      at character 0x25 (37)                          *
* Edit/Shift/Down    at character 0x25 (37)                          *
* Range enabled:  0033 - 0033                                        *
* Range enabled:  0063 - 0063                                        *
* Range enabled:  0062 - 0062                                        *
* Range enabled:  0063 - 0063                                        *
* Range disabled: 0063 - 0063                                        *
* Range enabled:  0067 - 0067                                        *
* Range enabled:  006D - 006D                                        *
* Range enabled:  0070 - 0070                                        *
* Range enabled:  0075 - 0075                                        *
* Edit/Shift/Down    at character 0x2F (47)                          *
* Edit/Shift/Down    at character 0x2F (47)                          *
* Edit/Shift/Down    at character 0x2F (47)                          *
* Edit/Insert/Right  at character 0x2F (47)                          *
* Edit/Insert/Right  at character 0x2F (47)                          *
* Edit/Insert/Right  at character 0x2F (47)                          *
* Edit/Insert/Right  at character 0x2F (47)                          *
* Edit/Insert/Left   at character 0x2F (47)                          *
* Edit/Insert/Left   at character 0x2F (47)                          *
* Edit/Insert/Left   at character 0x2F (47)                          *
* Edit/Insert/Left   at character 0x2F (47)                          *
* Edit/Shift/Down    at character 0x2F (47)                          *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTPro45Lt41;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro45Lt41_0025[164] = { /* code 0025, PERCENT SIGN */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ______XX,XX______,______XX,________,
  ____XXXX,XXXX____,______X_,________,
  ___XXX__,__XXX___,_____XX_,________,
  ___XX___,___XX___,_____X__,________,
  __XX____,___XXX__,____XX__,________,
  __XX____,____XX__,___XX___,________,
  __XX____,____XX__,___X____,________,
  __XX____,____XX__,__XX____,________,
  __XX____,____XX__,__X_____,________,
  __XX____,____XX__,_XX_____,________,
  __XX____,___XXX__,XX______,________,
  ___XX___,___XX___,XX______,________,
  ___XXX__,__XXX__X,X_______,________,
  ____XXXX,XXXX___X,______XX,X_______,
  ______XX,XX____XX,____XXXX,XXX_____,
  ________,_____XX_,___XXX__,_XXX____,
  ________,_____XX_,___XX___,__XX____,
  ________,____XX__,__XX____,___XX___,
  ________,____X___,__XX____,___XX___,
  ________,___XX___,__XX____,___XX___,
  ________,__XX____,__XX____,___XX___,
  ________,__XX____,__XX____,___XX___,
  ________,_XX_____,___XX___,__XX____,
  ________,_X______,___XXX__,_XXX____,
  ________,XX______,____XXXX,XXX_____,
  _______X,X_______,_____XXX,XX______,
  _______X,X_______,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro45Lt41_002F[123] = { /* code 002F, SOLIDUS */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,______XX,________,
  ________,______XX,________,
  ________,_____XX_,________,
  ________,_____XX_,________,
  ________,____XX__,________,
  ________,____XX__,________,
  ________,____X___,________,
  ________,___XX___,________,
  ________,___XX___,________,
  ________,__XX____,________,
  ________,__XX____,________,
  ________,__X_____,________,
  ________,_XX_____,________,
  ________,_XX_____,________,
  ________,XX______,________,
  ________,XX______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  _______X,X_______,________,
  ______XX,________,________,
  ______XX,________,________,
  _____XX_,________,________,
  _____XX_,________,________,
  _____X__,________,________,
  ____XX__,________,________,
  ____XX__,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro45Lt41_0033[123] = { /* code 0033, DIGIT THREE */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,XXXX____,________,
  _____XXX,XXXXXX__,________,
  ____XXX_,____XXX_,________,
  ____XX__,______XX,________,
  ___XX___,______XX,________,
  ___XX___,_______X,X_______,
  __XX____,_______X,X_______,
  __XX____,_______X,X_______,
  __XX____,_______X,X_______,
  ________,_______X,________,
  ________,______XX,________,
  ________,____XXX_,________,
  ________,XXXXXX__,________,
  ________,XXXXXXX_,________,
  ________,_____XXX,________,
  ________,_______X,X_______,
  ________,_______X,XX______,
  ________,________,XX______,
  _XX_____,________,XX______,
  _XX_____,________,XX______,
  _XX_____,________,XX______,
  __XX____,_______X,X_______,
  __XXX___,______XX,X_______,
  ___XXX__,____XXXX,________,
  ____XXXX,XXXXXXX_,________,
  _______X,XXXX____,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro45Lt41_0062[123] = { /* code 0062, LATIN SMALL LETTER B */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XX____,________,________,
  __XX____,________,________,
  __XX____,________,________,
  __XX____,________,________,
  __XX____,________,________,
  __XX____,________,________,
  __XX____,________,________,
  __XX____,XXXXX___,________,
  __XX__XX,XXXXXXX_,________,
  __XX_XXX,_____XXX,________,
  __XXXXX_,_______X,X_______,
  __XXX___,________,XX______,
  __XXX___,________,XX______,
  __XXX___,________,XXX_____,
  __XX____,________,_XX_____,
  __XX____,________,_XX_____,
  __XX____,________,_XX_____,
  __XX____,________,_XX_____,
  __XX____,________,_XX_____,
  __XX____,________,_XX_____,
  __XXX___,________,XXX_____,
  __XXX___,________,XX______,
  __XXXX__,_______X,XX______,
  __XXXXX_,______XX,X_______,
  __XX__XX,XXXXXXXX,________,
  __XX____,XXXXX___,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro45Lt41_0067[123] = { /* code 0067, LATIN SMALL LETTER G */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,XXX____X,X_______,
  _____XXX,XXXXX__X,X_______,
  ____XXX_,___XXX_X,X_______,
  ___XX___,_____XXX,X_______,
  __XX____,______XX,X_______,
  __XX____,______XX,X_______,
  _XX_____,_______X,X_______,
  _XX_____,_______X,X_______,
  _XX_____,_______X,X_______,
  _XX_____,_______X,X_______,
  _XX_____,_______X,X_______,
  _XX_____,_______X,X_______,
  _XX_____,_______X,X_______,
  __XX____,______XX,X_______,
  __XX____,______XX,X_______,
  ___XX___,_____XXX,X_______,
  ___XXXX_,___XXX_X,X_______,
  ____XXXX,XXXXX__X,X_______,
  _______X,XXX____X,X_______,
  ________,_______X,X_______,
  ________,_______X,X_______,
  __XX____,______XX,________,
  __XX____,______XX,________,
  ___XXX__,____XXX_,________,
  ____XXXX,XXXXXX__,________,
  ______XX,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro45Lt41_006D[164] = { /* code 006D, LATIN SMALL LETTER M */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  __XX___X,XXXX____,__XXXXX_,________,
  __XX__XX,XXXXX___,XXXXXXXX,________,
  __XX_XX_,___XXX_X,XX____XX,X_______,
  __XXXX__,____XX_X,X______X,X_______,
  __XXX___,_____XXX,________,XX______,
  __XXX___,_____XX_,________,XX______,
  __XX____,_____XX_,________,XX______,
  __XX____,_____XX_,________,XX______,
  __XX____,_____XX_,________,XX______,
  __XX____,_____XX_,________,XX______,
  __XX____,_____XX_,________,XX______,
  __XX____,_____XX_,________,XX______,
  __XX____,_____XX_,________,XX______,
  __XX____,_____XX_,________,XX______,
  __XX____,_____XX_,________,XX______,
  __XX____,_____XX_,________,XX______,
  __XX____,_____XX_,________,XX______,
  __XX____,_____XX_,________,XX______,
  __XX____,_____XX_,________,XX______,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro45Lt41_0070[123] = { /* code 0070, LATIN SMALL LETTER P */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XX____,XXXXX___,________,
  __XX__XX,XXXXXXX_,________,
  __XX_XXX,_____XXX,________,
  __XXXX__,_______X,X_______,
  __XXX___,________,XX______,
  __XXX___,________,XX______,
  __XX____,________,XXX_____,
  __XX____,________,_XX_____,
  __XX____,________,_XX_____,
  __XX____,________,_XX_____,
  __XX____,________,_XX_____,
  __XX____,________,_XX_____,
  __XX____,________,_XX_____,
  __XXX___,________,XXX_____,
  __XXX___,________,XX______,
  __XXXX__,_______X,XX______,
  __XXXXX_,______XX,X_______,
  __XX__XX,XXXXXXXX,________,
  __XX____,XXXXX___,________,
  __XX____,________,________,
  __XX____,________,________,
  __XX____,________,________,
  __XX____,________,________,
  __XX____,________,________,
  __XX____,________,________,
  __XX____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro45Lt41_0075[123] = { /* code 0075, LATIN SMALL LETTER U */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XX____,_______X,X_______,
  __XX____,_______X,X_______,
  __XX____,_______X,X_______,
  __XX____,_______X,X_______,
  __XX____,_______X,X_______,
  __XX____,_______X,X_______,
  __XX____,_______X,X_______,
  __XX____,_______X,X_______,
  __XX____,_______X,X_______,
  __XX____,_______X,X_______,
  __XX____,_______X,X_______,
  __XX____,_______X,X_______,
  __XX____,_______X,X_______,
  __XX____,______XX,X_______,
  __XX____,______XX,X_______,
  __XXX___,_____XXX,X_______,
  ___XXX__,____XXXX,X_______,
  ____XXXX,XXXXX__X,X_______,
  _____XXX,XXX____X,X_______,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontHelveticaNeueLTPro45Lt41_CharInfo[8] = {
   {  31,  31,  4, acGUI_FontHelveticaNeueLTPro45Lt41_0025 } /* code 0025 */
  ,{  20,  20,  3, acGUI_FontHelveticaNeueLTPro45Lt41_002F } /* code 002F */
  ,{  19,  19,  3, acGUI_FontHelveticaNeueLTPro45Lt41_0033 } /* code 0033 */
  ,{  20,  20,  3, acGUI_FontHelveticaNeueLTPro45Lt41_0062 } /* code 0062 */
  ,{  19,  19,  3, acGUI_FontHelveticaNeueLTPro45Lt41_0067 } /* code 0067 */
  ,{  29,  29,  4, acGUI_FontHelveticaNeueLTPro45Lt41_006D } /* code 006D */
  ,{  20,  20,  3, acGUI_FontHelveticaNeueLTPro45Lt41_0070 } /* code 0070 */
  ,{  19,  19,  3, acGUI_FontHelveticaNeueLTPro45Lt41_0075 } /* code 0075 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHelveticaNeueLTPro45Lt41_Prop8 = {
   0x0075 /* first character */
  ,0x0075 /* last character  */
  ,&GUI_FontHelveticaNeueLTPro45Lt41_CharInfo[  7] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHelveticaNeueLTPro45Lt41_Prop7 = {
   0x0070 /* first character */
  ,0x0070 /* last character  */
  ,&GUI_FontHelveticaNeueLTPro45Lt41_CharInfo[  6] /* address of first character */
  ,&GUI_FontHelveticaNeueLTPro45Lt41_Prop8 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHelveticaNeueLTPro45Lt41_Prop6 = {
   0x006D /* first character */
  ,0x006D /* last character  */
  ,&GUI_FontHelveticaNeueLTPro45Lt41_CharInfo[  5] /* address of first character */
  ,&GUI_FontHelveticaNeueLTPro45Lt41_Prop7 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHelveticaNeueLTPro45Lt41_Prop5 = {
   0x0067 /* first character */
  ,0x0067 /* last character  */
  ,&GUI_FontHelveticaNeueLTPro45Lt41_CharInfo[  4] /* address of first character */
  ,&GUI_FontHelveticaNeueLTPro45Lt41_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHelveticaNeueLTPro45Lt41_Prop4 = {
   0x0062 /* first character */
  ,0x0062 /* last character  */
  ,&GUI_FontHelveticaNeueLTPro45Lt41_CharInfo[  3] /* address of first character */
  ,&GUI_FontHelveticaNeueLTPro45Lt41_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHelveticaNeueLTPro45Lt41_Prop3 = {
   0x0033 /* first character */
  ,0x0033 /* last character  */
  ,&GUI_FontHelveticaNeueLTPro45Lt41_CharInfo[  2] /* address of first character */
  ,&GUI_FontHelveticaNeueLTPro45Lt41_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHelveticaNeueLTPro45Lt41_Prop2 = {
   0x002F /* first character */
  ,0x002F /* last character  */
  ,&GUI_FontHelveticaNeueLTPro45Lt41_CharInfo[  1] /* address of first character */
  ,&GUI_FontHelveticaNeueLTPro45Lt41_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHelveticaNeueLTPro45Lt41_Prop1 = {
   0x0025 /* first character */
  ,0x0025 /* last character  */
  ,&GUI_FontHelveticaNeueLTPro45Lt41_CharInfo[  0] /* address of first character */
  ,&GUI_FontHelveticaNeueLTPro45Lt41_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTPro45Lt41 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,41 /* height of font  */
  ,41 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHelveticaNeueLTPro45Lt41_Prop1}
  ,34 /* Baseline */
  ,19 /* Height of lowercase characters */
  ,26 /* Height of capital characters */
};

