/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        Font converter for emWin version 5.20                       *
*        Compiled Feb 19 2013, 11:55:34                              *
*        (C) 1998 - 2013 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: HelveticaNeueLT Pro 65 Md43.c                         *
* Font:        HelveticaNeueLT Pro 65 Md                             *
* Height:      43                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height: 43                                            *
* Range disabled: 0000 - FFFF                                        *
* Range enabled:  002F - 002F                                        *
* Range enabled:  0030 - 0035                                        *
* Range disabled: 0067 - 0067                                        *
* Range enabled:  0067 - 0067                                        *
* Range enabled:  006D - 006D                                        *
* Range enabled:  00B3 - 00B3                                        *
* Range enabled:  00B5 - 00B5                                        *
* Range enabled:  2265 - 2265                                        *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTPro65Md43;

/* Start of unicode area <Basic Latin> */

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md43_002F[ 86] = { /* code 002F, SOLIDUS */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,__XXX___,
  ________,_XXXX___,
  ________,_XXXX___,
  ________,XXXX____,
  ________,XXXX____,
  ________,XXXX____,
  _______X,XXX_____,
  _______X,XXX_____,
  ______XX,XXX_____,
  ______XX,XX______,
  ______XX,XX______,
  _____XXX,X_______,
  _____XXX,X_______,
  ____XXXX,X_______,
  ____XXXX,________,
  ____XXXX,________,
  ___XXXX_,________,
  ___XXXX_,________,
  ___XXXX_,________,
  __XXXX__,________,
  __XXXX__,________,
  _XXXX___,________,
  _XXXX___,________,
  _XXXX___,________,
  XXXX____,________,
  XXXX____,________,
  XXX_____,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md43_0030[129] = { /* code 0030, DIGIT ZERO */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _______X,XXXXX___,________,
  _____XXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,________,
  ___XXXXX,____XXXX,X_______,
  ___XXXX_,_____XXX,X_______,
  __XXXX__,______XX,XX______,
  __XXXX__,______XX,XX______,
  __XXXX__,______XX,XX______,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  __XXXX__,______XX,XX______,
  __XXXX__,______XX,XX______,
  __XXXX__,______XX,XX______,
  ___XXXX_,_____XXX,X_______,
  ___XXXXX,____XXXX,X_______,
  ____XXXX,XXXXXXXX,________,
  _____XXX,XXXXXXX_,________,
  _______X,XXXXX___,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md43_0031[129] = { /* code 0031, DIGIT ONE */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,__XXX___,________,
  ________,__XXX___,________,
  ________,_XXXX___,________,
  ________,XXXXX___,________,
  ______XX,XXXXX___,________,
  ___XXXXX,XXXXX___,________,
  ___XXXXX,XXXXX___,________,
  ___XXXXX,XXXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,_XXXX___,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md43_0032[129] = { /* code 0032, DIGIT TWO */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,XXXXX___,________,
  ______XX,XXXXXXXX,________,
  _____XXX,XXXXXXXX,X_______,
  ____XXXX,_____XXX,XX______,
  ___XXXX_,______XX,XX______,
  ___XXXX_,_______X,XXX_____,
  ___XXX__,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XX______,
  ________,_____XXX,XX______,
  ________,____XXXX,X_______,
  ________,___XXXXX,________,
  ________,_XXXXXX_,________,
  ________,XXXXXX__,________,
  _______X,XXXXX___,________,
  ______XX,XXXX____,________,
  _____XXX,XX______,________,
  ____XXXX,X_______,________,
  ___XXXXX,________,________,
  ___XXXX_,________,________,
  __XXXXX_,________,________,
  __XXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXX_____,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md43_0033[129] = { /* code 0033, DIGIT THREE */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,XXXXX___,________,
  ______XX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,________,
  ____XXXX,____XXXX,X_______,
  ___XXXX_,_____XXX,X_______,
  ___XXXX_,______XX,XX______,
  __XXXX__,______XX,XX______,
  __XXXX__,______XX,XX______,
  __XXXX__,______XX,XX______,
  ________,______XX,X_______,
  ________,_____XXX,X_______,
  ________,___XXXXX,X_______,
  ________,XXXXXXXX,________,
  ________,XXXXXXX_,________,
  ________,XXXXXXXX,X_______,
  ________,_____XXX,XX______,
  ________,______XX,XX______,
  ________,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  __XXXX__,______XX,XX______,
  __XXXX__,______XX,XX______,
  ___XXXXX,____XXXX,XX______,
  ___XXXXX,XXXXXXXX,X_______,
  _____XXX,XXXXXXX_,________,
  _______X,XXXXX___,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md43_0034[129] = { /* code 0034, DIGIT FOUR */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,____XXXX,________,
  ________,___XXXXX,________,
  ________,__XXXXXX,________,
  ________,__XXXXXX,________,
  ________,_XXXXXXX,________,
  ________,XXXXXXXX,________,
  ________,XXX_XXXX,________,
  _______X,XXX_XXXX,________,
  ______XX,XX__XXXX,________,
  ______XX,X___XXXX,________,
  _____XXX,X___XXXX,________,
  ____XXXX,____XXXX,________,
  ___XXXX_,____XXXX,________,
  ___XXXX_,____XXXX,________,
  __XXXX__,____XXXX,________,
  _XXXX___,____XXXX,________,
  _XXXX___,____XXXX,________,
  _XXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXX_____,
  ________,____XXXX,________,
  ________,____XXXX,________,
  ________,____XXXX,________,
  ________,____XXXX,________,
  ________,____XXXX,________,
  ________,____XXXX,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md43_0035[129] = { /* code 0035, DIGIT FIVE */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ____XXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,XX______,
  ___XXXX_,________,________,
  ___XXXX_,________,________,
  ___XXXX_,________,________,
  ___XXXX_,________,________,
  ___XXX__,________,________,
  ___XXX__,________,________,
  __XXXX__,XXXXXX__,________,
  __XXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,X_______,
  __XXXXX_,____XXXX,XX______,
  __XXXX__,______XX,XX______,
  ________,______XX,XXX_____,
  ________,_______X,XXX_____,
  ________,_______X,XXX_____,
  ________,_______X,XXX_____,
  ________,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,______XX,XX______,
  __XXXX__,______XX,XX______,
  __XXXXX_,_____XXX,X_______,
  ___XXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXX_,________,
  ______XX,XXXX____,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md43_0067[129] = { /* code 0067, LATIN SMALL LETTER G */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,XXXX____,XXXX____,
  _____XXX,XXXXXX__,XXXX____,
  ____XXXX,XXXXXXXX,XXXX____,
  ___XXXXX,_____XXX,XXXX____,
  __XXXXX_,______XX,XXXX____,
  __XXXX__,_______X,XXXX____,
  __XXXX__,_______X,XXXX____,
  _XXXX___,________,XXXX____,
  _XXXX___,________,XXXX____,
  _XXXX___,________,XXXX____,
  _XXXX___,________,XXXX____,
  _XXXX___,________,XXXX____,
  _XXXX___,________,XXXX____,
  _XXXXX__,_______X,XXXX____,
  __XXXX__,_______X,XXXX____,
  __XXXXX_,______XX,XXXX____,
  ___XXXXX,_____XXX,XXXX____,
  ____XXXX,XXXXXXX_,XXXX____,
  _____XXX,XXXXXX__,XXXX____,
  _______X,XXXXX___,XXXX____,
  ________,________,XXXX____,
  __XXXX__,________,XXXX____,
  __XXXX__,_______X,XXX_____,
  __XXXXXX,______XX,XXX_____,
  ___XXXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,________,
  _______X,XXXXXX__,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md43_006D[172] = { /* code 006D, LATIN SMALL LETTER M */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  __XXXX__,_XXXXX__,_____XXX,XXX_____,
  __XXXX_X,XXXXXXXX,___XXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,X_XXXXXX,XXXXX___,
  __XXXXXX,_____XXX,XXXX____,_XXXXX__,
  __XXXXX_,______XX,XXX_____,__XXXX__,
  __XXXXX_,______XX,XX______,__XXXX__,
  __XXXX__,______XX,XX______,__XXXX__,
  __XXXX__,______XX,XX______,__XXXX__,
  __XXXX__,______XX,XX______,__XXXX__,
  __XXXX__,______XX,XX______,__XXXX__,
  __XXXX__,______XX,XX______,__XXXX__,
  __XXXX__,______XX,XX______,__XXXX__,
  __XXXX__,______XX,XX______,__XXXX__,
  __XXXX__,______XX,XX______,__XXXX__,
  __XXXX__,______XX,XX______,__XXXX__,
  __XXXX__,______XX,XX______,__XXXX__,
  __XXXX__,______XX,XX______,__XXXX__,
  __XXXX__,______XX,XX______,__XXXX__,
  __XXXX__,______XX,XX______,__XXXX__,
  __XXXX__,______XX,XX______,__XXXX__,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

/* Start of unicode area <Latin-1 Supplement> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md43_00B3[ 86] = { /* code 00B3, SUPERSCRIPT THREE */
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ____XXXX,X_______,
  __XXXXXX,XXX_____,
  __XXXXXX,XXXX____,
  _XXXX___,XXXX____,
  _XXX____,_XXX____,
  ________,_XXX____,
  ________,XXX_____,
  _____XXX,XX______,
  ______XX,XXXX____,
  ________,_XXX____,
  ________,__XXX___,
  _XXX____,__XXX___,
  _XXX____,__XXX___,
  _XXXX___,_XXXX___,
  __XXXXXX,XXXX____,
  ___XXXXX,XXX_____,
  ____XXXX,X_______,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________,
  ________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md43_00B5[129] = { /* code 00B5, MICRO SIGN */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  __XXXX__,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  __XXXX__,_______X,XXX_____,
  __XXXX__,______XX,XXX_____,
  __XXXXX_,______XX,XXX_____,
  __XXXXXX,_____XXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXX_X,XXX_____,
  __XXXX_X,XXXX___X,XXX_____,
  __XXXX__,________,________,
  __XXXX__,________,________,
  __XXXX__,________,________,
  __XXXX__,________,________,
  __XXXX__,________,________,
  __XXXX__,________,________,
  __XXXX__,________,________,
  ________,________,________};

/* Start of unicode area <Mathematical Operators> */
GUI_CONST_STORAGE unsigned char acGUI_FontHelveticaNeueLTPro65Md43_00B6[129] = { /* code 2265, GREATER-THAN OR EQUAL TO */
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  _XX_____,________,________,
  _XXXXX__,________,________,
  _XXXXXXX,X_______,________,
  _XXXXXXX,XXXX____,________,
  ___XXXXX,XXXXXX__,________,
  ______XX,XXXXXXXX,X_______,
  ________,_XXXXXXX,XXXX____,
  ________,____XXXX,XXXXX___,
  ________,_______X,XXXXX___,
  ________,____XXXX,XXXXX___,
  ________,_XXXXXXX,XXXX____,
  ______XX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXX__,________,
  _XXXXXXX,XXX_____,________,
  _XXXXXXX,________,________,
  _XXXX___,________,________,
  _X______,________,________,
  ________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  _XXXXXXX,XXXXXXXX,XXXXX___,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________,
  ________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontHelveticaNeueLTPro65Md43_CharInfo[12] = {
   {  13,  13,  2, acGUI_FontHelveticaNeueLTPro65Md43_002F } /* code 002F */
  ,{  21,  21,  3, acGUI_FontHelveticaNeueLTPro65Md43_0030 } /* code 0030 */
  ,{  21,  21,  3, acGUI_FontHelveticaNeueLTPro65Md43_0031 } /* code 0031 */
  ,{  21,  21,  3, acGUI_FontHelveticaNeueLTPro65Md43_0032 } /* code 0032 */
  ,{  21,  21,  3, acGUI_FontHelveticaNeueLTPro65Md43_0033 } /* code 0033 */
  ,{  21,  21,  3, acGUI_FontHelveticaNeueLTPro65Md43_0034 } /* code 0034 */
  ,{  21,  21,  3, acGUI_FontHelveticaNeueLTPro65Md43_0035 } /* code 0035 */
  ,{  22,  22,  3, acGUI_FontHelveticaNeueLTPro65Md43_0067 } /* code 0067 */
  ,{  32,  32,  4, acGUI_FontHelveticaNeueLTPro65Md43_006D } /* code 006D */
  ,{  13,  13,  2, acGUI_FontHelveticaNeueLTPro65Md43_00B3 } /* code 00B3 */
  ,{  21,  21,  3, acGUI_FontHelveticaNeueLTPro65Md43_00B5 } /* code 00B5 */
  ,{  22,  22,  3, acGUI_FontHelveticaNeueLTPro65Md43_00B6 } /* code 2265 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHelveticaNeueLTPro65Md43_Prop6 = {
   0x00B6 /* first character */
  ,0x00B6 /* last character  */
  ,&GUI_FontHelveticaNeueLTPro65Md43_CharInfo[ 11] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHelveticaNeueLTPro65Md43_Prop5 = {
   0x00B5 /* first character */
  ,0x00B5 /* last character  */
  ,&GUI_FontHelveticaNeueLTPro65Md43_CharInfo[ 10] /* address of first character */
  ,&GUI_FontHelveticaNeueLTPro65Md43_Prop6 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHelveticaNeueLTPro65Md43_Prop4 = {
   0x00B3 /* first character */
  ,0x00B3 /* last character  */
  ,&GUI_FontHelveticaNeueLTPro65Md43_CharInfo[  9] /* address of first character */
  ,&GUI_FontHelveticaNeueLTPro65Md43_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHelveticaNeueLTPro65Md43_Prop3 = {
   0x006D /* first character */
  ,0x006D /* last character  */
  ,&GUI_FontHelveticaNeueLTPro65Md43_CharInfo[  8] /* address of first character */
  ,&GUI_FontHelveticaNeueLTPro65Md43_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHelveticaNeueLTPro65Md43_Prop2 = {
   0x0067 /* first character */
  ,0x0067 /* last character  */
  ,&GUI_FontHelveticaNeueLTPro65Md43_CharInfo[  7] /* address of first character */
  ,&GUI_FontHelveticaNeueLTPro65Md43_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontHelveticaNeueLTPro65Md43_Prop1 = {
   0x002F /* first character */
  ,0x0035 /* last character  */
  ,&GUI_FontHelveticaNeueLTPro65Md43_CharInfo[  0] /* address of first character */
  ,&GUI_FontHelveticaNeueLTPro65Md43_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontHelveticaNeueLTPro65Md43 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,43 /* height of font  */
  ,43 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontHelveticaNeueLTPro65Md43_Prop1}
  ,35 /* Baseline */
  ,20 /* Height of lowercase characters */
  ,27 /* Height of capital characters */
};

