/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontSong16.c                                          *
* Font:        ËÎÌו                                                  *
* Height:      16                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  16                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\byb\Desktop\FontSong16.txt             *
* Edit/Shift/Right      at character 0x8394 (33684)                  *
* Edit/Shift/Left       at character 0x8394 (33684)                  *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong16;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_5B50[ 32] = { /* code 5B50 */
  ________,________,
  _XXXXXXX,XXXXX___,
  ________,___X____,
  ________,__X_____,
  ________,_X______,
  _______X,X_______,
  _______X,________,
  XXXXXXXX,XXXXXXX_,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _______X,________,
  _____X_X,________,
  ______X_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_5B89[ 32] = { /* code 5B89 */
  ______X_,________,
  _______X,________,
  __XXXXXX,XXXXXX__,
  __X_____,_____X__,
  _X____X_,____X___,
  ______X_,________,
  ______X_,________,
  XXXXXXXX,XXXXXXX_,
  _____X__,__X_____,
  ____X___,__X_____,
  ___XX___,_X______,
  _____XX_,_X______,
  _______X,X_______,
  ______X_,_XX_____,
  ____XX__,___X____,
  _XXX____,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_5BCC[ 32] = { /* code 5BCC */
  ______X_,________,
  _______X,________,
  _XXXXXXX,XXXXXXX_,
  _X______,______X_,
  X_XXXXXX,XXXXXX__,
  ________,________,
  ___XXXXX,XXXX____,
  ___X____,___X____,
  ___XXXXX,XXXX____,
  ________,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X_____,____X___};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_7535[ 32] = { /* code 7535 */
  _______X,________,
  _______X,________,
  _______X,________,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X___,
  __X____X,____X___,
  __X____X,____X___,
  __XXXXXX,XXXXX___,
  __X____X,____X_X_,
  _______X,______X_,
  _______X,______X_,
  ________,XXXXXXX_};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong16_83B1[ 32] = { /* code 83B1 */
  ____X___,__X_____,
  ____X___,__X_____,
  XXXXXXXX,XXXXXXX_,
  ____X__X,__X_____,
  _______X,________,
  __XXXXXX,XXXXX___,
  _______X,________,
  ___X___X,___X____,
  ____X__X,__X_____,
  _XXXXXXX,XXXXXX__,
  ______XX,X_______,
  _____X_X,_X______,
  ____X__X,__X_____,
  __XX___X,___XX___,
  XX_____X,_____XX_,
  _______X,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontFontSong16_CharInfo[5] = {
   {  16,  16,  2, acGUI_FontFontSong16_5B50 } /* code 5B50 */
  ,{  16,  16,  2, acGUI_FontFontSong16_5B89 } /* code 5B89 */
  ,{  16,  16,  2, acGUI_FontFontSong16_5BCC } /* code 5BCC */
  ,{  16,  16,  2, acGUI_FontFontSong16_7535 } /* code 7535 */
  ,{  16,  16,  2, acGUI_FontFontSong16_83B1 } /* code 83B1 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop5 = {
   0x83B1 /* first character */
  ,0x83B1 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[  4] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop4 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[  3] /* address of first character */
  ,&GUI_FontFontSong16_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop3 = {
   0x5BCC /* first character */
  ,0x5BCC /* last character  */
  ,&GUI_FontFontSong16_CharInfo[  2] /* address of first character */
  ,&GUI_FontFontSong16_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop2 = {
   0x5B89 /* first character */
  ,0x5B89 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[  1] /* address of first character */
  ,&GUI_FontFontSong16_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong16_Prop1 = {
   0x5B50 /* first character */
  ,0x5B50 /* last character  */
  ,&GUI_FontFontSong16_CharInfo[  0] /* address of first character */
  ,&GUI_FontFontSong16_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong16 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,16 /* height of font  */
  ,16 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFontSong16_Prop1}
  ,14 /* Baseline */
  ,7 /* Height of lowercase characters */
  ,11 /* Height of capital characters */
};

