/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.32                      *
*        Compiled Oct  8 2015, 11:58:55                              *
*                                                                    *
*        (c) 1998 - 2015 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: FontSong32.c                                          *
* Font:        ËÎÌו                                                  *
* Height:      33                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  33                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\byb\Desktop\FontSong16.txt             *
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong32;

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFontSong32_5B50[132] = { /* code 5B50 */
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,XX______,
  ______XX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,________,_______X,XXX_____,
  ________,________,______XX,________,
  ________,________,_____XX_,________,
  ________,________,___XX___,________,
  ________,________,__XX____,________,
  ________,_______X,XX______,________,
  ________,_______X,XX______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,___X____,
  ________,_______X,X_______,__XXX___,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,__XXXXXX,X_______,________,
  ________,_____XXX,________,________,
  ________,______X_,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong32_5B89[132] = { /* code 5B89 */
  ________,________,________,________,
  ________,________,________,________,
  ________,______X_,________,________,
  ________,_______X,X_______,________,
  ________,________,XX______,________,
  ________,________,XX______,________,
  ______X_,________,XX______,___X____,
  ______X_,________,________,__XXX___,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXX___,
  _____XX_,________,________,__X_____,
  ____XXX_,_____X__,________,_X______,
  ____XX__,_____XXX,________,________,
  ________,_____XX_,________,________,
  ________,____XX__,________,___X____,
  ________,____XX__,________,__XXX___,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,___XX___,_____XX_,________,
  ________,___XX___,_____XX_,________,
  ________,__XX____,____XX__,________,
  ________,__XX____,____XX__,________,
  ________,_XX_____,___XX___,________,
  ________,_XX_____,__XXX___,________,
  ________,__XXX___,__XX____,________,
  ________,_____XXX,XXX_____,________,
  ________,________,XXXXX___,________,
  ________,_______X,XX_XXXX_,________,
  ________,______XX,_____XXX,XX______,
  ________,____XXX_,_______X,XXX_____,
  ________,__XXX___,________,_XXX____,
  _______X,XXX_____,________,__XX____,
  ___XXXX_,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong32_5BCC[132] = { /* code 5BCC */
  ________,________,________,________,
  ________,________,________,________,
  ________,______XX,________,________,
  ________,_______X,X_______,________,
  ________,_______X,X_______,________,
  _____X__,________,X_______,___X____,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ____XX__,________,________,__XX____,
  ____XX__,________,______X_,__X_____,
  ___XX___,________,_____XXX,_X______,
  ________,XXXXXXXX,XXXXXXXX,X_______,
  ________,________,________,________,
  ________,_X______,_____XX_,________,
  ________,_XXXXXXX,XXXXXXXX,________,
  ________,_XX_____,_____XX_,________,
  ________,_XX_____,_____XX_,________,
  ________,_XX_____,_____XX_,________,
  ________,_XXXXXXX,XXXXXXX_,________,
  ________,_X______,________,________,
  ______X_,________,________,X_______,
  _______X,XXXXXXXX,XXXXXXXX,XX______,
  _______X,_______X,X______X,X_______,
  _______X,_______X,X______X,X_______,
  _______X,_______X,X______X,X_______,
  _______X,XXXXXXXX,XXXXXXXX,X_______,
  _______X,_______X,X______X,X_______,
  _______X,_______X,X______X,X_______,
  _______X,_______X,X______X,X_______,
  _______X,XXXXXXXX,XXXXXXXX,X_______,
  _______X,________,_______X,X_______,
  _______X,________,_______X,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong32_7535[132] = { /* code 7535 */
  ________,________,________,________,
  ________,________,________,________,
  ________,______XX,________,________,
  ________,______XX,X_______,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  ________,______XX,________,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XXX,XXXXXXXX,XXXXXXXX,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XX_,______XX,________,XX______,
  _____XXX,XXXXXXXX,XXXXXXXX,XX______,
  _____XX_,______XX,________,X_______,
  _____XX_,______XX,________,________,
  ________,______XX,________,___X____,
  ________,______XX,________,____X___,
  ________,______XX,________,____X___,
  ________,______XX,________,___XX___,
  ________,______XX,X_______,___XXX__,
  ________,_______X,XXXXXXXX,XXXXX___,
  ________,________,________,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFontSong32_83B1[132] = { /* code 83B1 */
  ________,________,________,________,
  ________,________,________,________,
  ________,___XX___,____X___,________,
  ________,___XX___,____XX__,________,
  ________,___XX___,____XX__,___X____,
  ________,___XX___,____XX__,__XXX___,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,___XX___,____XX__,________,
  ________,___XX__X,X___XX__,________,
  ________,___X___X,X_______,________,
  ________,_______X,X_______,_XX_____,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ________,_______X,X____X__,________,
  ________,XX_____X,X_____XX,________,
  ________,_XX____X,X____XXX,________,
  ________,__XX___X,X____XX_,________,
  ________,__XX___X,X___XX__,________,
  ________,___X___X,X___X___,___XX___,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ___X____,_____XXX,XX______,________,
  ________,____XX_X,X_X_____,________,
  ________,____XX_X,X__X____,________,
  ________,___XX__X,X__XX___,________,
  ________,__XX___X,X___XX__,________,
  ________,_XX____X,X____XX_,________,
  ________,XX_____X,X_____XX,X_______,
  ______XX,X______X,X______X,XXXX____,
  _____XX_,_______X,X_______,XXXXXX__,
  ___XX___,_______X,X_______,__XX____,
  __X_____,_______X,X_______,________,
  ________,_______X,X_______,________,
  ________,________,________,________,
  ________,________,________,________};

GUI_CONST_STORAGE GUI_CHARINFO GUI_FontFontSong32_CharInfo[5] = {
   {  32,  32,  4, acGUI_FontFontSong32_5B50 } /* code 5B50 */
  ,{  32,  32,  4, acGUI_FontFontSong32_5B89 } /* code 5B89 */
  ,{  32,  32,  4, acGUI_FontFontSong32_5BCC } /* code 5BCC */
  ,{  32,  32,  4, acGUI_FontFontSong32_7535 } /* code 7535 */
  ,{  32,  32,  4, acGUI_FontFontSong32_83B1 } /* code 83B1 */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong32_Prop5 = {
   0x83B1 /* first character */
  ,0x83B1 /* last character  */
  ,&GUI_FontFontSong32_CharInfo[  4] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP *)0 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong32_Prop4 = {
   0x7535 /* first character */
  ,0x7535 /* last character  */
  ,&GUI_FontFontSong32_CharInfo[  3] /* address of first character */
  ,&GUI_FontFontSong32_Prop5 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong32_Prop3 = {
   0x5BCC /* first character */
  ,0x5BCC /* last character  */
  ,&GUI_FontFontSong32_CharInfo[  2] /* address of first character */
  ,&GUI_FontFontSong32_Prop4 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong32_Prop2 = {
   0x5B89 /* first character */
  ,0x5B89 /* last character  */
  ,&GUI_FontFontSong32_CharInfo[  1] /* address of first character */
  ,&GUI_FontFontSong32_Prop3 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT_PROP GUI_FontFontSong32_Prop1 = {
   0x5B50 /* first character */
  ,0x5B50 /* last character  */
  ,&GUI_FontFontSong32_CharInfo[  0] /* address of first character */
  ,&GUI_FontFontSong32_Prop2 /* pointer to next GUI_FONT_PROP */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFontSong32 = {
   GUI_FONTTYPE_PROP /* type of font    */
  ,33 /* height of font  */
  ,33 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFontSong32_Prop1}
  ,27 /* Baseline */
  ,14 /* Height of lowercase characters */
  ,22 /* Height of capital characters */
};

